/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InfoHubRouteImport } from './routes/info-hub'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CmeRouteImport } from './routes/cme'
import { Route as ClinsightsRouteImport } from './routes/clinsights'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoHubRoute = InfoHubRouteImport.update({
  id: '/info-hub',
  path: '/info-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CmeRoute = CmeRouteImport.update({
  id: '/cme',
  path: '/cme',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinsightsRoute = ClinsightsRouteImport.update({
  id: '/clinsights',
  path: '/clinsights',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clinsights': typeof ClinsightsRoute
  '/cme': typeof CmeRoute
  '/contact': typeof ContactRoute
  '/info-hub': typeof InfoHubRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clinsights': typeof ClinsightsRoute
  '/cme': typeof CmeRoute
  '/contact': typeof ContactRoute
  '/info-hub': typeof InfoHubRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clinsights': typeof ClinsightsRoute
  '/cme': typeof CmeRoute
  '/contact': typeof ContactRoute
  '/info-hub': typeof InfoHubRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clinsights'
    | '/cme'
    | '/contact'
    | '/info-hub'
    | '/login'
    | '/news'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clinsights'
    | '/cme'
    | '/contact'
    | '/info-hub'
    | '/login'
    | '/news'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clinsights'
    | '/cme'
    | '/contact'
    | '/info-hub'
    | '/login'
    | '/news'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClinsightsRoute: typeof ClinsightsRoute
  CmeRoute: typeof CmeRoute
  ContactRoute: typeof ContactRoute
  InfoHubRoute: typeof InfoHubRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info-hub': {
      id: '/info-hub'
      path: '/info-hub'
      fullPath: '/info-hub'
      preLoaderRoute: typeof InfoHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cme': {
      id: '/cme'
      path: '/cme'
      fullPath: '/cme'
      preLoaderRoute: typeof CmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinsights': {
      id: '/clinsights'
      path: '/clinsights'
      fullPath: '/clinsights'
      preLoaderRoute: typeof ClinsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClinsightsRoute: ClinsightsRoute,
  CmeRoute: CmeRoute,
  ContactRoute: ContactRoute,
  InfoHubRoute: InfoHubRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
